name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality Check
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run tests
        run: poetry run python manage.py test

      - name: Linter (temporariamente desativado)
        run: echo "wemake-python-styleguide removido para evitar bug do Python 3.1"
